config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'





  get '/help', to: 'static_pages#help'

  get '/about', to: 'static_pages#about'

  get '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'

  get '/login',to: 'sessions#new'

  post '/login',to: 'sessions#create'

  get '/logout',to: 'sessions#destroy'







  root 'static_pages#home'

  resources:users



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :password, presence: true, length:{minimum: 8}
    validates :name, presence: true
    # VALID_EMAIL_REGEX= /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i



    validates :email, presence: true

    # format:{with:VALID_EMAIL_REGEX}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def hello


    end

    include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create

    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])

     log_in user

    rmove_user_to_url

    else

      flash.now[:danger] = "Incorrect email/password"

      render 'new'

    end

  end

  def destroy

    log_out

    redirect_to root_path

  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end


  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :user_logged_in, only: [:edit, :update., :show]
before_action :check_user_correct, only: [:edit, :update, :show]

  def new

    if !@user

    @user=User.new

  end

end

  def show

  @user= User.find(params[:id])

  end

  def create

   @user= User.new(user_req)

    if @user.save

      log_in @user

      flash[:success]="Registration Successful"

redirect_to @user

   else

    render 'new'

    end

  end



def edit

  @user =User.find(params[:id])



end



def update

  @user=User.find(params[:id])

  if @user.update(user_req)

  flash[:success]="Profile Updated"

  redirect_to @user

  else

  render 'edit'

  end

end
def user_logged_in

  unless logged_in?
    save_user_location
    flash[:danger]="Login first"
    redirect_to login_path
  end 
end
def check_correct_user
@user = User.find(params[:id])
unless @user == current_user
  flash[:danger]="Wrong user"
  redirect_to root_path

end



  private

  def user_req

    params.require(:user).permit(:name,:email,:password,:password_confirmation)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def display_title(page_title=" ")

        if page_title.empty?

            'no title'

        else

            page_title + "- MyWebsite"

        end

    end
end

app/helpers/sessions_helper.rb
module SessionsHelper



    def log_in(user)

       

        session[:user_id]=user.id

    

    end



    def current_user

        

        if session[:user_id]

            

                

            @current_user ||= User.find_by(id:session[:user_id])

        end

    

    end

    def save_user_location
        session[:user_url] = request.original_url 
    end

    def move_user_to_url
        redirect_to(session[:user_url])
        session.delete(:user_url)

    end



    def logged_in?

        

        

        !current_user.nil?

        

    

    end



    def log_out

        

        session.delete(:user_id)

        @current_user=nil



    end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper



    def my_gravatar(user)

        

        g_id = Digest::MD5::hexdigest(user.email.downcase)

        g_url="http://secure.gravatar.com/avatar/#{g_id}"

        image_tag(g_url,alt:user.name,class:"gravatar")

    end



end

app/views/layouts/_error_messages.html.erb
# <% if @user.errors.any? %>

<div>
<p>the form contains errors : </p>

</div>

<ul>
<% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %> </li>
    <%end%>

</ul>
# <% end %>

app/views/layouts/_footer.html.erb
<footer>

    <p>Copyright 2022.All rights reserved</p>

    </footer>

app/views/layouts/_form.html.erb
<%= form_with(model: @user, data: { turbo: false }) do |f| %>

    <%= render 'layouts/error_messages' %>

    <%= f.label :name %>

    <%= f.text_field :name %>

    

    <%= f.label :email %>

    <%= f.email_field :email %>

    

    <%= f.label :password %>

    <%= f.password_field :password %>

    

    <%= f.label :password_confirmation %>

    <%= f.password_field :password_confirmation %>

    

    <%= f.submit yield (:button_text) %>

    <% end %>

app/views/layouts/_header.html.erb
<header>

<div class="header-container">

<div>

<!<img src ="https://logos-world.net/wp-content/uploads/2022/01/Looney-Tunes-Logo-1985.png">

<%=link_to image_tag("logo.png",alt:"Logo",width:"200",height:"100"),"#" %>

</div>

<div class="heading">

<%=link_to "My Website",root_path,id:"logo" %>

</div>

</div>

<nav class="nav-bar">

<%= link_to "Home",root_path %>

<%= link_to "About",about_path %>

<%= link_to "Contact",contact_path %>

<%= link_to "Help",help_path %>



<% if logged_in? %>

<%= link_to "Update Profile",edit_user_path(current_user) %>

<%= link_to "Log Out", logout_path, method: :delete %>

<% else %>

<%= link_to "Login", login_path %>

<%= link_to "Sign Up", signup_path %>

<% end %>



</nav>

</div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

  <head>

  <title> <%= display_title(yield(:title))%> </title>

    

    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>

    <%= csp_meta_tag %>



    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>

  </head>



  <body>

<%= render 'layouts/header'%>



<div class="body-cont">

    <%= yield %>
    <% flash.each do |m_type,msg| %>

      <div><%=msg %></div>
    
      <% end %>
    
    

    <%= debug(params) if Rails.env.development? %>
    render 'footer'

</div>

    <%= render 'layouts/footer' %>

  </body>

</html>

app/views/static_pages/about.html.erb
<% provide(:title,"About") %>

<h1> Welcome to about page </h1>

<table>

<tr>

<th>Name<th>

<th>CreationDate</th>

<th>Copyright<th>

</tr>

<h2>here is data</h2>

<tr>

<td>MyWebsite<td>

<td>29-11-2022</td>

<td>2022</td>

</tr>

</table>

</body>
</html>

app/views/static_pages/contact.html.erb
<h1>Welcome to My Contacts page</h1>

<address>
Reach us at <a href="https://www.operative.com/">Operative.com</a>.<br>
Srijith,HR<br>
Operative India<br>
Banglore&Pune<br>
Phonenumber :- 9876543210
</address>


<div>
<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15554.430700403695!2d77.604139!3d12.9329184!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x7d3b5698526bd6a3!2sOperative%20India!5e0!3m2!1sen!2sin!4v1661795373843!5m2!1sen!2sin" 
width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>       
            </div>

app/views/static_pages/help.html.erb
<% provide(:title,"HELP") %>



<!DOCTYPE html>



<html>



<head>



<title> <%= yield(:title)%> MyWebsite </title>



</head>



<body>



<h1>Welcome to the help page</h1>



<p>We provide help on:</p>



<ol>



            <li>Resources</li>



            <li>Contents</li>



            <li>Templates</li>

        </ol>

</body>

</html>

app/views/static_pages/home.html.erb
<% provide(:title,"Home") %>
<h1>This is HOME!!</h1>
<h2> This is home but smaller </h2>
Click on the link to find Ruby documentation

<a href ="https://www.ruby-lang.org/en/documentation/">Link Text</a> 

<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/users/edit.html.erb
<% provide(:title,"Edit Profile") %>



<% provide(:button_text,"Update") %>

<h1> Edit your profile </h1>



<div>

<%= render 'layouts/form' %>

</div>



<div>

<%= my_gravatar @user %>

<a href="https://gravatar.com/emails" target="_blank">Change</a>



</div>

app/views/users/new.html.erb
<% provide(:title,"SIGN UP") %>

<% provide(:button_text,"Sign Up") %>

<h1>Sign Up </h1>

<div>

<%= render 'layouts/form' %>

</div>

app/views/users/show.html.erb
<%= my_gravatar @user %>
<%= @user.name %>
<%= @user.email %>